services:
  postgres-user:
    image: postgres:15
    container_name: postgres-user
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  postgres-product:
    image: postgres:15
    container_name: postgres-product
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data

  postgres-order:
    image: postgres:15
    container_name: postgres-order
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data

  postgres-payment:
    image: postgres:15
    container_name: postgres-payment
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data

  postgres-notification:
    image: postgres:15
    container_name: postgres-notification
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: notification
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    volumes:
      - notification_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres-user
      - postgres-product
      - postgres-order
      - postgres-payment
      - postgres-notification

volumes:
  user_db_data:
  product_db_data:
  order_db_data:
  payment_db_data:
  notification_db_data:
  pgadmin_data:
