spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: ${USER_SERVICE_URL:http://userservice:8080}
          predicates:
            - Path=/api/users/**

        - id: auth
          uri: ${USER_SERVICE_URL:http://userservice:8080}
          predicates:
            - Path=/api/auth/**

        - id: productservice
          uri: ${PRODUCT_SERVICE_URL:http://productservice:8080}
          predicates:
            - Path=/api/products/**

        - id: orderservice
          uri: ${ORDER_SERVICE_URL:http://orderservice:8080}
          predicates:
            - Path=/api/orders/**

        - id: paymentservice
          uri: ${PAYMENT_SERVICE_URL:http://paymentservice:8080}
          predicates:
            - Path=/api/payments/**
server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:8AxlbLwQ+6BD0yJ63kG93DG4ES8VyD3Yiy0v8qrCy2s=}
