spring:
  application:
    name: apigateway
  cloud:
    gateway:
        routes:
          - id: authservice
            uri: lb://authservice
            predicates:
              - Path=/api/auth/**

          - id: userservice
            uri: lb://userservice
            predicates:
              - Path=/api/users/**

          - id: productservice
            uri: lb://productservice
            predicates:
              - Path=/api/products/**

          - id: orderservice
            uri: lb://orderservice
            predicates:
              - Path=/api/orders/**

          - id: paymentservice
            uri: lb://paymentservice
            predicates:
              - Path=/api/payments/**

          - id: notificationservice
            uri: lb://notificationservice
            predicates:
              - Path=/api/notifications/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/order

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
