spring:
  application:
    name: apigateway
  cloud:
    gateway:
        routes:
          - id: authservice
            uri: lb://authservice
            predicates:
              - Path=/api/auth/**

          - id: userservice
            uri: lb://userservice
            predicates:
              - Path=/api/users/**

          - id: productservice
            uri: lb://productservice
            predicates:
              - Path=/api/products/**

          - id: orderservice
            uri: lb://orderservice
            predicates:
              - Path=/api/orders/**

          - id: paymentservice
            uri: lb://paymentservice
            predicates:
              - Path=/api/payments/**

          - id: notificationservice
            uri: lb://notificationservice
            predicates:
              - Path=/api/notifications/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/order}
          jwk-set-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/order}/protocol/openid-connect/certs

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8061/eureka/
  instance:
    hostname: host.docker.internal
    prefer-ip-address: false
