spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update   
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: userservice-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8061/eureka/
  instance:
    hostname: host.docker.internal
    prefer-ip-address: false

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:9090}
  realm: order
  client-id: order
  client-secret: ${KEYCLOAK_CLIENT_SECRET:V8TIkxbK17PLOJPwa3MUETNjlz4c9mC}