spring:
  application:
    name: userservice

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: update   
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: userservice-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

server:
  port: ${SERVER_PORT:8081}

jwt:
  secret: ${JWT_SECRET:8AxlbLwQ+6BD0yJ63kG93DG4ES8VyD3Yiy0v8qrCy2s=}
  access-token-ttl-seconds: ${JWT_ACCESS_TOKEN_TTL_SECONDS:900}
  refresh-token-ttl-days: ${JWT_REFRESH_TOKEN_TTL_DAYS:7}

