spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update   
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: userservice-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

server:
  port: 8080
