spring:
  application:
    name: authservice

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

server:
  port: 8086 # Default to 8086

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8061/eureka/}
  instance:
    hostname: host.docker.internal
    prefer-ip-address: false

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:9090}
  realm: order
  client-id: order
  client-secret: ${KEYCLOAK_CLIENT_SECRET:V8TIkxbK17PLOJPwa3MUETNjlz4c9mC}

