server:
  port: 8086

spring:
  application:
    name: notificationservice
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.mailtrap.io # Placeholder, use mailtrap or similar for testing
    port: 2525
    username: test
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
