server:
  port: 8080

spring:
  application:
    name: notificationservice
  datasource:
    url: jdbc:postgresql://postgres:5432/notification_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
